### ISSUE TITLE
Ultracite fails on biome v2.2

### ISSUE THREAD

**Issue by maelp** [haydenbleasel/ultracite#244]
**Describe the bug**
When updating to Biome 2.2, we get lot of "non-existent rules" errors

**Ultracite version**
Latest

**To Reproduce**
pnpm lint

<img width="1636" height="368" alt="Image" src="https://github.com/user-attachments/assets/75ad4d4b-4200-40fd-b89e-da7f0507b8f4" />

**Comment by raviriley** [comment]
It seems that with the current configuration, during the time gap between when a new Biome version is released and when the corresponding update is made to ultracite, running ultracite will fail (assuming the Biome update contains breaking changes) even if I have a specific Biome version pinned in my repo. This is a huge flaw

**Comment by haydenbleasel** [comment]
Working on it right now. This is more an unfortunate situation as Biome has moved a [massive amount of rules](https://biomejs.dev/internals/changelog/) out of the nursery in this update. Hopefully as they become more stable, updates should get easier and quicker.

**Comment by haydenbleasel** [comment]
Fixed! Update to the latest version with:

```
pnpm add -D ultracite@5.1.3 @biomejs/biome@2.2.0
```

**Comment by maelp** [comment]
@haydenbleasel nice! although now I have weird noSolidDestructuredProps issues on a React project? do you think it comes from ultracite? not sure why a solidjs rule would be applied there

**Comment by haydenbleasel** [comment]
@maelp quite possibly - i'll look into biome domains today and see if we can have these rules apply magically to the right projects. if not, i'll just disable the rule.

**Comment by rortan134** [comment]
> Fixed! Update to the latest version with:
> 
> ```
> pnpm add -D ultracite@5.1.3 @biomejs/biome@2.2.0
> ```

Hey is there any sort of caching I might have to delete after upgrading? I'm still getting unknown key errors
